// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Flight_radar

#include "ui.h"
#include "platform.h"
#include "opensky_client.h"
#include "radar.h"
#include "main.h"

#include <stdlib.h>   /* atof */

/*
void wifi_connect_btn_cb(lv_event_t *e)
{
	// Your code here
}
	*/

static void msgbox_event_cb(lv_event_t *e)
{
	lv_obj_t *obj = lv_event_get_current_target(e);

	const char *txt =
		lv_msgbox_get_active_btn_text(obj);

	if (txt && strcmp(txt, "Forget") == 0)
	{
		platform_forget_wifi_creds();

		lv_label_set_text(
			uic_wifiName,
			"No WiFi Selected");

		lv_textarea_set_text(
			uic_wifiPassword,
			"");

		lv_textarea_set_text(
			uic_wifiStatus,
			"Not connected");
	}

	lv_msgbox_close(obj);
}

static void api_msgbox_event_cb(
	lv_event_t *e)
{
	lv_obj_t *obj =
		lv_event_get_current_target(e);

	const char *txt =
		lv_msgbox_get_active_btn_text(obj);

	if (txt &&
		strcmp(txt, "Forget") == 0)
	{
		platform_forget_opensky_creds();
		platform_restart();
	}

	lv_msgbox_close(obj);
}

void forgetWifi(lv_event_t *e)
{
	static const char *btns[] =
		{
			"Cancel",
			"Forget",
			""};

	lv_obj_t *mbox =
		lv_msgbox_create(
			NULL,
			"Forget WiFi?",
			"Stored WiFi credentials will be removed.\n And device will be resetarted",
			btns,
			false);

	lv_obj_center(mbox);

	lv_obj_add_event_cb(
		mbox,
		msgbox_event_cb,
		LV_EVENT_VALUE_CHANGED,
		NULL);
}

void Radar_SelectPrev(lv_event_t *e)
{
	if (gAircraftCount <= 0)
	{
		selectedAircraft = -1;
		return;
	}

	selectedAircraft--;

	if (selectedAircraft < 0)
	{
		selectedAircraft =
			gAircraftCount - 1;
	}

	strcpy(
		selectedIcao24,
		gAircraft[selectedAircraft].icao24);

	Radar_Refresh();
	UpdateSelectedAircraftUI();
}

void Radar_SelectNext(lv_event_t *e)
{
	if (gAircraftCount <= 0)
	{
		selectedAircraft = -1;
		return;
	}

	selectedAircraft++;

	if (selectedAircraft >= gAircraftCount)
	{
		selectedAircraft = 0;
	}

	strcpy(
		selectedIcao24,
		gAircraft[selectedAircraft].icao24);

	Radar_Refresh();
	UpdateSelectedAircraftUI();
}

void editCoords(lv_event_t *e)
{
	float lat =
		atof(
			lv_textarea_get_text(
				uic_TextLat));

	float lon =
		atof(
			lv_textarea_get_text(
				uic_TextLon));

	/*
float rangeKm =
atof(
lv_textarea_get_text(
	uic_TextRange));
*/

	SetRadarSettings(
		lat,
		lon,
		50.0f);

	Radar_Refresh();
}

void toggleLabels(lv_event_t *e)
{
	lv_event_code_t code =
		lv_event_get_code(e);

	lv_obj_t *obj =
		lv_event_get_target(e);

	if (code == LV_EVENT_VALUE_CHANGED)
	{
		showAircraftLabels =
			lv_obj_has_state(
				obj,
				LV_STATE_CHECKED);

		Radar_Refresh();

		LV_LOG_USER(
			"Labels: %s",
			showAircraftLabels
				? "On"
				: "Off");
	}
}

void toggleUnits(lv_event_t *e)
{
	lv_event_code_t code =
		lv_event_get_code(e);

	lv_obj_t *obj =
		lv_event_get_target(e);

	if (code == LV_EVENT_VALUE_CHANGED)
	{
		bool imperial =
			lv_obj_has_state(
				obj,
				LV_STATE_CHECKED);

		SetUnits(imperial);

		LV_LOG_USER(
			"Units: %s",
			imperial
				? "Imperial"
				: "Metric");
	}
}

void rangeUp(lv_event_t *e)
{
	(void)e;
	SetRadarRange(GetRadarRange() + 10.0f);
}

void refreshUp(lv_event_t *e)
{
	(void)e;
	int s = GetRefreshInterval() + 2;
	SetRefreshInterval(s);
	if (uic_LabelRefresh) {
		lv_label_set_text_fmt(uic_LabelRefresh, "Refresh: %ds", s);
	}
}

void refreshDown(lv_event_t *e)
{
	(void)e;
	int s = GetRefreshInterval() - 2;
	SetRefreshInterval(s);
	if (uic_LabelRefresh) {
		lv_label_set_text_fmt(uic_LabelRefresh, "Refresh: %ds", s);
	}
}

void toggleTrail(lv_event_t *e)
{
	lv_event_code_t code = lv_event_get_code(e);
	lv_obj_t *obj = lv_event_get_target(e);

	if (code == LV_EVENT_VALUE_CHANGED)
	{
		bool on = lv_obj_has_state(obj, LV_STATE_CHECKED);
		Radar_SetTrail(on);
		platform_storage_set_u8("radar", "trail", on ? 1 : 0);
		Radar_Refresh();
		LV_LOG_USER("Trail: %s", on ? "On" : "Off");
	}
}

/* Sync the right-rail trail switch (Screen1) with the state in NVS, called by
   LoadTrail() in app_state.c. */
void syncTrailSwitchState(void)
{
	/* Screen3 holds the canonical uic_SwitchTrail; Screen1 holds a peer
	   switch we keep in the same NVS-controlled state. Both must show the
	   same CHECKED flag. */
	extern lv_obj_t * ui_SwitchTrailRowMain;
	if (!ui_SwitchTrailRowMain) return;
	if (showSelectedTrail)
		lv_obj_add_state(ui_SwitchTrailRowMain, LV_STATE_CHECKED);
	else
		lv_obj_clear_state(ui_SwitchTrailRowMain, LV_STATE_CHECKED);
}

void rangeDown(lv_event_t *e)
{
	(void)e;
	SetRadarRange(GetRadarRange() - 10.0f);
}

void Radar_TapSelect(lv_event_t *e)
{
	lv_event_code_t code =
		lv_event_get_code(e);

	if (code != LV_EVENT_CLICKED)
		return;

	lv_indev_t *indev =
		lv_indev_get_act();

	if (!indev)
		return;

	lv_point_t pt;
	lv_indev_get_point(indev, &pt);

	int idx =
		Radar_PickAircraft(
			pt.x,
			pt.y);

	if (idx >= 0 && idx < gAircraftCount)
	{
		selectedAircraft = idx;

		strcpy(
			selectedIcao24,
			gAircraft[idx].icao24);

		UpdateSelectedAircraftUI();
		Radar_Refresh();
	}
}

void forgetAPI(lv_event_t *e)
{
	static const char *btns[] =
		{
			"Cancel",
			"Forget",
			""};

	lv_obj_t *mbox =
		lv_msgbox_create(
			NULL,
			"Forget OpenSky API?",
			"Stored API credentials will be removed.\nDevice will restart.",
			btns,
			false);

	lv_obj_center(mbox);

	lv_obj_add_event_cb(
		mbox,
		api_msgbox_event_cb,
		LV_EVENT_VALUE_CHANGED,
		NULL);
}
