// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Flight_radar

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_ContainerLeft;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_PanelLeft;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_ContainerCard1;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_LabelPlaneCount;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_ContainerCard2;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_LabelAPIRefresh;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_PanelLeft1;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_ContainerCard3;
extern lv_obj_t * ui_LabelCoords;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_ContainerCard8;
extern lv_obj_t * ui_Label23;
extern void ui_event_Switch3(lv_event_t * e);
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_ContainerCardUnits;
extern lv_obj_t * ui_LabelUnits;
extern void ui_event_SwitchUnits(lv_event_t * e);
extern lv_obj_t * ui_SwitchUnits;
extern lv_obj_t * ui_ContainerCardTrail;
extern lv_obj_t * ui_LabelTrail;
extern void ui_event_SwitchTrail(lv_event_t * e);
extern lv_obj_t * ui_SwitchTrail;
extern lv_obj_t * ui_PanelRight;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_ContainerCard4;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_LabelCraftName;
extern lv_obj_t * ui_ContainerCard5;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_LabelCraftAlt;
extern lv_obj_t * ui_ContainerCard6;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_LabelCraftSpeed;
extern lv_obj_t * ui_ContainerCard7;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_LabelCraftOrigin;
extern lv_obj_t * ui_ContainerCard9;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_LabelCraftCategory;
extern lv_obj_t * ui_ContainerCard10;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_LabelCraftHeading;
extern lv_obj_t * ui_ContainerCardClimb;
extern lv_obj_t * ui_LabelClimbTitle;
extern lv_obj_t * ui_LabelCraftClimb;
extern lv_obj_t * ui_PanelRadar;
extern lv_obj_t * ui_Imageradar;
extern lv_obj_t * ui_RadarTitle;
extern lv_obj_t * ui_RadarLoc;
extern lv_obj_t * ui_LabelAPIRefreshBig;
extern lv_obj_t * ui_LabelWaitingBanner;
extern lv_obj_t * ui_ContainerLegend;
extern lv_obj_t * ui_LegendClimb;
extern lv_obj_t * ui_LegendDescend;
extern lv_obj_t * ui_LegendGround;
extern lv_obj_t * ui_LegendLevel;
extern void ui_event_ButtonLeft(lv_event_t * e);
extern lv_obj_t * ui_ButtonLeft;
extern lv_obj_t * ui_Label7;
extern void ui_event_ButtonRight(lv_event_t * e);
extern lv_obj_t * ui_ButtonRight;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label29;
extern void ui_event_ButtonRangeUp(lv_event_t * e);
extern lv_obj_t * ui_ButtonRangeUp;
extern lv_obj_t * ui_LabelRangeUp;
extern void ui_event_ButtonRangeDown(lv_event_t * e);
extern lv_obj_t * ui_ButtonRangeDown;
extern lv_obj_t * ui_LabelRangeDown;
extern lv_obj_t * ui_ContainerRange;
extern lv_obj_t * ui_ContainerRefresh;
extern lv_obj_t * ui_ButtonRefreshUp;
extern lv_obj_t * ui_ButtonRefreshDown;
extern lv_obj_t * ui_LabelRefreshUp;
extern lv_obj_t * ui_LabelRefreshDown;
extern lv_obj_t * ui_LabelRefresh;
extern lv_obj_t * ui_ContainerSettings;
extern lv_obj_t * ui_LabelSettings;
extern lv_obj_t * ui_ContainerTrailRowMain;
extern lv_obj_t * ui_LabelTrailTextMain;
extern lv_obj_t * ui_SwitchTrailRowMain;
extern lv_obj_t * ui_PanelBottom;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_LabelWifiName;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_LabelIP;
extern lv_obj_t * ui_LabelIPData;
extern lv_obj_t * ui_LabelClock;
extern lv_obj_t * ui_DialogConfigReq;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_DialogCoord;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Container9;
extern void ui_event_TextLat(lv_event_t * e);
extern lv_obj_t * ui_TextLat;
extern void ui_event_TextLon(lv_event_t * e);
extern lv_obj_t * ui_TextLon;
extern lv_obj_t * ui_Container7;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label27;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_KeyboardCoord;
// CUSTOM VARIABLES
extern lv_obj_t * uic_PanelLeft;
extern lv_obj_t * uic_LabelRange;
extern lv_obj_t * uic_SwitchUnits;
extern lv_obj_t * uic_LabelCraftClimb;
extern lv_obj_t * uic_ContainerCard1;
extern lv_obj_t * uic_LabelPlaneCount;
extern lv_obj_t * uic_ContainerCard2;
extern lv_obj_t * uic_LabelAPIRefresh;
extern lv_obj_t * uic_LabelCoords;
extern lv_obj_t * uic_PanelRight;
extern lv_obj_t * uic_LabelCraftName;
extern lv_obj_t * uic_LabelCraftAlt;
extern lv_obj_t * uic_LabelCraftSpeed;
extern lv_obj_t * uic_LabelCraftOrigin;
extern lv_obj_t * uic_LabelCraftCategory;
extern lv_obj_t * uic_LabelCraftHeading;
extern lv_obj_t * uic_PanelRadar;
extern lv_obj_t * uic_Imageradar;
extern lv_obj_t * uic_ButtonLeft;
extern lv_obj_t * uic_ButtonRight;
extern lv_obj_t * uic_PanelBottom;
extern lv_obj_t * uic_LabelConnection;
extern lv_obj_t * uic_LabelWifiName;
extern lv_obj_t * uic_LabelIP;
extern lv_obj_t * uic_LabelIPData;
extern lv_obj_t * uic_LabelClock;
extern lv_obj_t * uic_LabelConnection;
extern lv_obj_t * uic_LabelRefresh;
extern lv_obj_t * uic_SwitchTrail;
extern lv_obj_t * uic_DialogConfigReq;
extern lv_obj_t * uic_DialogCoord;
extern lv_obj_t * uic_TextLat;
extern lv_obj_t * uic_TextLon;
extern lv_obj_t * uic_KeyboardCoord;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

