// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Flight_radar

#include "../ui.h"
#include "main.h"   /* GetRadarRange, GetRefreshInterval */

lv_obj_t * uic_KeyboardCoord;
lv_obj_t * uic_TextLon;
lv_obj_t * uic_TextLat;
lv_obj_t * uic_DialogCoord;
lv_obj_t * uic_DialogConfigReq;
lv_obj_t * uic_LabelIPData;
lv_obj_t * uic_LabelClock;
lv_obj_t * uic_LabelRefresh;
lv_obj_t * uic_LabelIP;
lv_obj_t * uic_LabelWifiName;
lv_obj_t * uic_LabelConnection;
lv_obj_t * uic_PanelBottom;
lv_obj_t * uic_ButtonRight;
lv_obj_t * uic_ButtonLeft;
lv_obj_t * uic_Imageradar;
lv_obj_t * uic_PanelRadar;
lv_obj_t * uic_LabelCraftHeading;
lv_obj_t * uic_LabelCraftCategory;
lv_obj_t * uic_LabelCraftOrigin;
lv_obj_t * uic_LabelCraftSpeed;
lv_obj_t * uic_LabelCraftAlt;
lv_obj_t * uic_LabelCraftName;
lv_obj_t * uic_PanelRight;
lv_obj_t * uic_LabelCoords;
lv_obj_t * uic_LabelAPIRefresh;
lv_obj_t * uic_ContainerCard2;
lv_obj_t * uic_LabelPlaneCount;
lv_obj_t * uic_ContainerCard1;
lv_obj_t * uic_PanelLeft;
lv_obj_t * uic_LabelRange;
lv_obj_t * uic_SwitchUnits;
lv_obj_t * uic_SwitchTrail;
lv_obj_t * uic_LabelCraftClimb;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_ContainerLeft = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_PanelLeft = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_ContainerCard1 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_LabelPlaneCount = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_ContainerCard2 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_LabelAPIRefresh = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_PanelLeft1 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_ContainerCard3 = NULL;
lv_obj_t * ui_LabelCoords = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_ContainerCard8 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Switch3 = NULL;
lv_obj_t * ui_PanelRight = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_ContainerCard4 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_LabelCraftName = NULL;
lv_obj_t * ui_ContainerCard5 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_LabelCraftAlt = NULL;
lv_obj_t * ui_ContainerCard6 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_LabelCraftSpeed = NULL;
lv_obj_t * ui_ContainerCard7 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_LabelCraftOrigin = NULL;
lv_obj_t * ui_ContainerCard9 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_LabelCraftCategory = NULL;
lv_obj_t * ui_ContainerCard10 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_LabelCraftHeading = NULL;
lv_obj_t * ui_PanelRadar = NULL;
lv_obj_t * ui_Imageradar = NULL;
lv_obj_t * ui_ButtonLeft = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_ButtonRight = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_PanelBottom = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_LabelWifiName = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_LabelIP = NULL;
lv_obj_t * ui_LabelIPData = NULL;
lv_obj_t * ui_LabelClock = NULL;
lv_obj_t * ui_DialogConfigReq = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label5 = NULL;
/* ui_DialogCoord / coord textareas / keyboard are now owned by Screen3 —
   declared extern in this header, defined in ui_Screen3.c */
lv_obj_t * ui_ContainerCardUnits = NULL;
lv_obj_t * ui_LabelUnits = NULL;
lv_obj_t * ui_SwitchUnits = NULL;
lv_obj_t * ui_ContainerCardTrail = NULL;
lv_obj_t * ui_LabelTrail = NULL;
lv_obj_t * ui_SwitchTrail = NULL;
lv_obj_t * ui_ContainerCardClimb = NULL;
lv_obj_t * ui_LabelClimbTitle = NULL;
lv_obj_t * ui_LabelCraftClimb = NULL;
lv_obj_t * ui_ButtonRangeDown = NULL;
lv_obj_t * ui_LabelRangeDown = NULL;
lv_obj_t * ui_ButtonRangeUp = NULL;
lv_obj_t * ui_LabelRangeUp = NULL;
lv_obj_t * ui_RadarTitle = NULL;
lv_obj_t * ui_RadarLoc = NULL;
lv_obj_t * ui_LabelAPIRefreshBig = NULL;
lv_obj_t * ui_LabelWaitingBanner = NULL;
lv_obj_t * ui_ContainerLegend = NULL;
lv_obj_t * ui_LegendClimb = NULL;
lv_obj_t * ui_LegendDescend = NULL;
lv_obj_t * ui_LegendGround = NULL;
lv_obj_t * ui_LegendLevel = NULL;
lv_obj_t * ui_ContainerRange = NULL;
lv_obj_t * ui_ContainerRefresh = NULL;
lv_obj_t * ui_ButtonRefreshUp = NULL;
lv_obj_t * ui_ButtonRefreshDown = NULL;
lv_obj_t * ui_LabelRefreshUp = NULL;
lv_obj_t * ui_LabelRefreshDown = NULL;
lv_obj_t * ui_LabelRefresh = NULL;
lv_obj_t * ui_ContainerSettings = NULL;
lv_obj_t * ui_LabelSettings = NULL;
lv_obj_t * ui_ContainerTrailRowMain = NULL;
lv_obj_t * ui_LabelTrailTextMain = NULL;
lv_obj_t * ui_SwitchTrailRowMain = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DialogCoord, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Switch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        toggleLabels(e);
    }
}

void ui_event_ButtonLeft(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Radar_SelectPrev(e);
    }
}

void ui_event_ButtonRight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Radar_SelectNext(e);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_TextLat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_KeyboardCoord,  ui_TextLat);
    }
}

void ui_event_TextLon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_KeyboardCoord,  ui_TextLon);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        editCoords(e);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DialogCoord, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_SwitchUnits(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        toggleUnits(e);
    }
}

void ui_event_SwitchTrail(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        toggleTrail(e);
    }
}

void ui_event_ButtonRangeUp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        rangeUp(e);
    }
}

void ui_event_ButtonRangeDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        rangeDown(e);
    }
}

void ui_event_ButtonRefreshUp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        refreshUp(e);
    }
}

void ui_event_ButtonRefreshDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        refreshDown(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x0A1024), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

#define CARD(o) do { \
        lv_obj_remove_style_all(o); \
        lv_obj_clear_flag(o, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); \
        ui_object_set_themeable_style_property(o, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_CardBG); \
        ui_object_set_themeable_style_property(o, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_CardBG); \
    } while (0)
#define GRAY(l) do { \
        ui_object_set_themeable_style_property(l, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Gray); \
        ui_object_set_themeable_style_property(l, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Gray); \
    } while (0)

    /* ============ Radar hero (left, full screen height) ============ */
    ui_PanelRadar = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_PanelRadar);
    lv_obj_set_width(ui_PanelRadar, 560);
    lv_obj_set_height(ui_PanelRadar, 480);
    lv_obj_set_x(ui_PanelRadar, 0);
    lv_obj_set_y(ui_PanelRadar, 0);
    lv_obj_set_align(ui_PanelRadar, LV_ALIGN_TOP_LEFT);
    lv_obj_clear_flag(ui_PanelRadar, LV_OBJ_FLAG_SCROLLABLE);

    ui_Imageradar = lv_img_create(ui_PanelRadar);
    lv_obj_set_width(ui_Imageradar, 460);
    lv_obj_set_height(ui_Imageradar, 460);
    lv_obj_set_align(ui_Imageradar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Imageradar, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(ui_Imageradar, LV_OBJ_FLAG_SCROLLABLE);

    /* Title + clock — top-left of the radar panel */
    ui_RadarTitle = lv_label_create(ui_PanelRadar);
    lv_obj_set_x(ui_RadarTitle, 2);
    lv_obj_set_y(ui_RadarTitle, 12);
    lv_label_set_text(ui_RadarTitle, "Flight Radar");
    lv_obj_set_style_text_color(ui_RadarTitle, lv_color_hex(0x7CFFB0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RadarTitle, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Trail toggle button removed — the trail is now controlled by the
       right-rail switch (ui_SwitchTrailRowMain) only. The radar-panel
       toggle button was used to also gate the speed vector, which has
       been removed. */

    ui_LabelClock = lv_label_create(ui_PanelRadar);
    lv_obj_set_x(ui_LabelClock, 2);
    lv_obj_set_y(ui_LabelClock, 36);
    lv_label_set_text(ui_LabelClock, "--:--");
    lv_obj_set_style_text_color(ui_LabelClock, lv_color_hex(0x4E4FE0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelClock, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Loc — bottom-left of the radar panel */
    ui_RadarLoc = lv_label_create(ui_PanelRadar);
    lv_obj_set_x(ui_RadarLoc, 12);
    lv_obj_set_y(ui_RadarLoc, -8);
    lv_obj_set_align(ui_RadarLoc, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_RadarLoc, "Loc: 0.0000, 0.0000");
    lv_obj_set_style_text_color(ui_RadarLoc, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RadarLoc, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* API-age readout — small bottom-right of the radar panel, kept out of
       the way of the radar dial itself. */
    ui_LabelAPIRefreshBig = lv_label_create(ui_PanelRadar);
    lv_obj_set_align(ui_LabelAPIRefreshBig, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_x(ui_LabelAPIRefreshBig, -8);
    lv_obj_set_y(ui_LabelAPIRefreshBig, -8);
    lv_label_set_text(ui_LabelAPIRefreshBig, "API: --");
    lv_obj_set_style_text_color(ui_LabelAPIRefreshBig, lv_color_hex(0x7CFFB0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAPIRefreshBig, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Waiting banner — shown on startup, hidden after the first successful
       OpenSky fetch. Centred on the radar panel. */
    ui_LabelWaitingBanner = lv_label_create(ui_PanelRadar);
    lv_obj_set_align(ui_LabelWaitingBanner, LV_ALIGN_CENTER);
    lv_obj_set_y(ui_LabelWaitingBanner, -20);
    lv_label_set_text(ui_LabelWaitingBanner, "Waiting for OpenSky API...");
    lv_obj_set_style_text_color(ui_LabelWaitingBanner, lv_color_hex(0xFFD66E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWaitingBanner, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelWaitingBanner, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    /* hidden by default; AppState_ShowWaitingBanner() flips it on at boot
       and AppState_HideWaitingBanner() flips it off after the first fetch */

    /* Colour key — anchored top-right of the radar panel (above the dial),
       stacked title + 4 colour/label rows. Tells the user what each plane
       colour means. */
    ui_ContainerLegend = lv_obj_create(ui_PanelRadar);
    lv_obj_remove_style_all(ui_ContainerLegend);
    lv_obj_set_align(ui_ContainerLegend, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_x(ui_ContainerLegend, -8);
    lv_obj_set_y(ui_ContainerLegend, 8);
    lv_obj_set_size(ui_ContainerLegend, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(ui_ContainerLegend, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_row(ui_ContainerLegend, 2, 0);

    /* Each row: tiny coloured square + state name. */
    static const struct { const char *text; uint32_t color; } rows[4] = {
        {"Climbing",    0x00E000},   /* green */
        {"Descending",  0xE02020},   /* red */
        {"Level flight",0xFFFFFF},   /* white */
        {"Ground",      0x808080},   /* grey */
    };
    lv_obj_t *labels[4] = {NULL, NULL, NULL, NULL};
    for (int k = 0; k < 4; k++) {
        lv_obj_t *row = lv_obj_create(ui_ContainerLegend);
        lv_obj_remove_style_all(row);
        lv_obj_set_size(row, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
        lv_obj_set_flex_flow(row, LV_FLEX_FLOW_ROW);
        lv_obj_set_flex_align(row, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
        lv_obj_set_style_pad_column(row, 6, 0);

        lv_obj_t *swatch = lv_obj_create(row);
        lv_obj_remove_style_all(swatch);
        lv_obj_set_size(swatch, 12, 12);
        lv_obj_set_style_bg_color(swatch, lv_color_hex(rows[k].color), 0);
        lv_obj_set_style_bg_opa(swatch, LV_OPA_COVER, 0);
        lv_obj_set_style_border_color(swatch, lv_color_hex(0x404040), 0);
        lv_obj_set_style_border_width(swatch, 1, 0);

        labels[k] = lv_label_create(row);
        lv_label_set_text(labels[k], rows[k].text);
        lv_obj_set_style_text_color(labels[k], lv_color_hex(rows[k].color), 0);
        lv_obj_set_style_text_font(labels[k], &lv_font_montserrat_12, 0);
    }
    ui_LegendClimb   = labels[0];
    ui_LegendDescend = labels[1];
    ui_LegendLevel   = labels[2];
    ui_LegendGround  = labels[3];

    /* ============ Right rail: status + selected craft + controls ============ */
    ui_PanelRight = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_PanelRight);
    lv_obj_set_width(ui_PanelRight, 240);
    lv_obj_set_height(ui_PanelRight, 480);
    lv_obj_set_align(ui_PanelRight, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_PanelRight, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelRight, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelRight, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_pad_left(ui_PanelRight, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelRight, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelRight, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelRight, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelRight, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* aircraft count + "aircraft nearby" — top of rail */
    ui_Container4 = lv_obj_create(ui_PanelRight);
    CARD(ui_Container4);
    lv_obj_set_width(ui_Container4, lv_pct(100));
    lv_obj_set_height(ui_Container4, LV_SIZE_CONTENT);
    lv_obj_set_style_pad_top(ui_Container4, 4, 0);
    lv_obj_set_style_pad_bottom(ui_Container4, 4, 0);
    ui_LabelPlaneCount = lv_label_create(ui_Container4);
    lv_obj_set_align(ui_LabelPlaneCount, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelPlaneCount, "0 aircraft nearby");
    lv_obj_set_style_text_color(ui_LabelPlaneCount, lv_color_hex(0x08FF00), 0);
    lv_obj_set_style_text_font(ui_LabelPlaneCount, &lv_font_montserrat_14, 0);

    /* big callsign */
    ui_ContainerCard4 = lv_obj_create(ui_PanelRight);
    CARD(ui_ContainerCard4);
    lv_obj_set_width(ui_ContainerCard4, lv_pct(100));
    lv_obj_set_height(ui_ContainerCard4, 50);
    ui_Label17 = lv_label_create(ui_ContainerCard4);
    lv_obj_set_x(ui_Label17, 10); lv_obj_set_y(ui_Label17, 2);
    lv_label_set_text(ui_Label17, "Callsign");
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_12, 0); GRAY(ui_Label17);
    ui_LabelCraftName = lv_label_create(ui_ContainerCard4);
    lv_obj_set_align(ui_LabelCraftName, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_x(ui_LabelCraftName, 10); lv_obj_set_y(ui_LabelCraftName, -4);
    lv_label_set_text(ui_LabelCraftName, "—");
    lv_obj_set_style_text_color(ui_LabelCraftName, lv_color_hex(0xF98A00), 0);
    lv_obj_set_style_text_font(ui_LabelCraftName, &lv_font_montserrat_20, 0);

    /* origin */
    ui_ContainerCard7 = lv_obj_create(ui_PanelRight);
    CARD(ui_ContainerCard7);
    lv_obj_set_width(ui_ContainerCard7, lv_pct(100));
    lv_obj_set_height(ui_ContainerCard7, 40);
    ui_Label20 = lv_label_create(ui_ContainerCard7);
    lv_obj_set_x(ui_Label20, 10); lv_obj_set_y(ui_Label20, 2);
    lv_label_set_text(ui_Label20, "Origin");
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_12, 0); GRAY(ui_Label20);
    ui_LabelCraftOrigin = lv_label_create(ui_ContainerCard7);
    lv_obj_set_align(ui_LabelCraftOrigin, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_x(ui_LabelCraftOrigin, 10); lv_obj_set_y(ui_LabelCraftOrigin, -4);
    lv_label_set_text(ui_LabelCraftOrigin, "—");
    lv_obj_set_style_text_color(ui_LabelCraftOrigin, lv_color_hex(0x00A4F9), 0);
    lv_obj_set_style_text_font(ui_LabelCraftOrigin, &lv_font_montserrat_16, 0);

    /* altitude (climb-coloured) */
    ui_ContainerCard5 = lv_obj_create(ui_PanelRight);
    CARD(ui_ContainerCard5);
    lv_obj_set_width(ui_ContainerCard5, lv_pct(100));
    lv_obj_set_height(ui_ContainerCard5, 44);
    ui_Label18 = lv_label_create(ui_ContainerCard5);
    lv_obj_set_x(ui_Label18, 10); lv_obj_set_y(ui_Label18, 2);
    lv_label_set_text(ui_Label18, "Altitude");
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_12, 0); GRAY(ui_Label18);
    ui_LabelCraftAlt = lv_label_create(ui_ContainerCard5);
    lv_obj_set_align(ui_LabelCraftAlt, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_x(ui_LabelCraftAlt, 10); lv_obj_set_y(ui_LabelCraftAlt, -4);
    lv_label_set_text(ui_LabelCraftAlt, "—");
    lv_obj_set_style_text_color(ui_LabelCraftAlt, lv_color_hex(0x00F912), 0);
    lv_obj_set_style_text_font(ui_LabelCraftAlt, &lv_font_montserrat_16, 0);

    /* speed */
    ui_ContainerCard6 = lv_obj_create(ui_PanelRight);
    CARD(ui_ContainerCard6);
    lv_obj_set_width(ui_ContainerCard6, lv_pct(100));
    lv_obj_set_height(ui_ContainerCard6, 44);
    ui_Label19 = lv_label_create(ui_ContainerCard6);
    lv_obj_set_x(ui_Label19, 10); lv_obj_set_y(ui_Label19, 2);
    lv_label_set_text(ui_Label19, "Speed");
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_12, 0); GRAY(ui_Label19);
    ui_LabelCraftSpeed = lv_label_create(ui_ContainerCard6);
    lv_obj_set_align(ui_LabelCraftSpeed, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_x(ui_LabelCraftSpeed, 10); lv_obj_set_y(ui_LabelCraftSpeed, -4);
    lv_label_set_text(ui_LabelCraftSpeed, "—");
    lv_obj_set_style_text_color(ui_LabelCraftSpeed, lv_color_hex(0xDDF900), 0);
    lv_obj_set_style_text_font(ui_LabelCraftSpeed, &lv_font_montserrat_16, 0);

    /* heading */
    ui_ContainerCard10 = lv_obj_create(ui_PanelRight);
    CARD(ui_ContainerCard10);
    lv_obj_set_width(ui_ContainerCard10, lv_pct(100));
    lv_obj_set_height(ui_ContainerCard10, 44);
    ui_Label26 = lv_label_create(ui_ContainerCard10);
    lv_obj_set_x(ui_Label26, 10); lv_obj_set_y(ui_Label26, 2);
    lv_label_set_text(ui_Label26, "Heading");
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_12, 0); GRAY(ui_Label26);
    ui_LabelCraftHeading = lv_label_create(ui_ContainerCard10);
    lv_obj_set_align(ui_LabelCraftHeading, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_x(ui_LabelCraftHeading, 10); lv_obj_set_y(ui_LabelCraftHeading, -4);
    lv_label_set_text(ui_LabelCraftHeading, "—");
    lv_obj_set_style_text_color(ui_LabelCraftHeading, lv_color_hex(0x00A4F9), 0);
    lv_obj_set_style_text_font(ui_LabelCraftHeading, &lv_font_montserrat_16, 0);

    /* climb */
    ui_ContainerCardClimb = lv_obj_create(ui_PanelRight);
    CARD(ui_ContainerCardClimb);
    lv_obj_set_width(ui_ContainerCardClimb, lv_pct(100));
    lv_obj_set_height(ui_ContainerCardClimb, 44);
    ui_LabelClimbTitle = lv_label_create(ui_ContainerCardClimb);
    lv_obj_set_x(ui_LabelClimbTitle, 10); lv_obj_set_y(ui_LabelClimbTitle, 2);
    lv_label_set_text(ui_LabelClimbTitle, "Climb");
    lv_obj_set_style_text_font(ui_LabelClimbTitle, &lv_font_montserrat_12, 0); GRAY(ui_LabelClimbTitle);
    ui_LabelCraftClimb = lv_label_create(ui_ContainerCardClimb);
    lv_obj_set_align(ui_LabelCraftClimb, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_x(ui_LabelCraftClimb, 10); lv_obj_set_y(ui_LabelCraftClimb, -4);
    lv_label_set_text(ui_LabelCraftClimb, "—");
    lv_obj_set_style_text_color(ui_LabelCraftClimb, lv_color_hex(0x00A4F9), 0);
    lv_obj_set_style_text_font(ui_LabelCraftClimb, &lv_font_montserrat_16, 0);

    /* Range cluster — label "Range: 50 km" + [-] [+] in the rail */
    ui_ContainerRange = lv_obj_create(ui_PanelRight);
    lv_obj_remove_style_all(ui_ContainerRange);
    lv_obj_set_width(ui_ContainerRange, lv_pct(100));
    lv_obj_set_height(ui_ContainerRange, 36);
    lv_obj_set_flex_flow(ui_ContainerRange, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerRange, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_column(ui_ContainerRange, 6, 0);

    ui_ButtonRangeDown = lv_btn_create(ui_ContainerRange);
    lv_obj_set_width(ui_ButtonRangeDown, 32);
    lv_obj_set_height(ui_ButtonRangeDown, 32);
    lv_obj_add_flag(ui_ButtonRangeDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_ButtonRangeDown, LV_OBJ_FLAG_SCROLLABLE);
    ui_LabelRangeDown = lv_label_create(ui_ButtonRangeDown);
    lv_obj_set_align(ui_LabelRangeDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRangeDown, "-");
    lv_obj_set_style_text_font(ui_LabelRangeDown, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_ContainerRange);
    lv_label_set_text_fmt(ui_Label29, "Range: %d km", (int)GetRadarRange());
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0x7CFFB0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRangeUp = lv_btn_create(ui_ContainerRange);
    lv_obj_set_width(ui_ButtonRangeUp, 32);
    lv_obj_set_height(ui_ButtonRangeUp, 32);
    lv_obj_add_flag(ui_ButtonRangeUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_ButtonRangeUp, LV_OBJ_FLAG_SCROLLABLE);
    ui_LabelRangeUp = lv_label_create(ui_ButtonRangeUp);
    lv_obj_set_align(ui_LabelRangeUp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRangeUp, "+");
    lv_obj_set_style_text_font(ui_LabelRangeUp, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Refresh cluster — label "Refresh: 22s" + [-] [+] */
    ui_ContainerRefresh = lv_obj_create(ui_PanelRight);
    lv_obj_remove_style_all(ui_ContainerRefresh);
    lv_obj_set_width(ui_ContainerRefresh, lv_pct(100));
    lv_obj_set_height(ui_ContainerRefresh, 36);
    lv_obj_set_flex_flow(ui_ContainerRefresh, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerRefresh, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_column(ui_ContainerRefresh, 6, 0);

    ui_ButtonRefreshDown = lv_btn_create(ui_ContainerRefresh);
    lv_obj_set_width(ui_ButtonRefreshDown, 32);
    lv_obj_set_height(ui_ButtonRefreshDown, 32);
    lv_obj_add_flag(ui_ButtonRefreshDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_ButtonRefreshDown, LV_OBJ_FLAG_SCROLLABLE);
    ui_LabelRefreshDown = lv_label_create(ui_ButtonRefreshDown);
    lv_obj_set_align(ui_LabelRefreshDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRefreshDown, "-");
    lv_obj_set_style_text_font(ui_LabelRefreshDown, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRefresh = lv_label_create(ui_ContainerRefresh);
    lv_label_set_text_fmt(ui_LabelRefresh, "Refresh: %ds", GetRefreshInterval());
    lv_obj_set_style_text_color(ui_LabelRefresh, lv_color_hex(0x7CFFB0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelRefresh, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRefreshUp = lv_btn_create(ui_ContainerRefresh);
    lv_obj_set_width(ui_ButtonRefreshUp, 32);
    lv_obj_set_height(ui_ButtonRefreshUp, 32);
    lv_obj_add_flag(ui_ButtonRefreshUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_ButtonRefreshUp, LV_OBJ_FLAG_SCROLLABLE);
    ui_LabelRefreshUp = lv_label_create(ui_ButtonRefreshUp);
    lv_obj_set_align(ui_LabelRefreshUp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRefreshUp, "+");
    lv_obj_set_style_text_font(ui_LabelRefreshUp, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* WiFi row — connection + ssid */
    ui_Container1 = lv_obj_create(ui_PanelRight);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, lv_pct(100));
    lv_obj_set_height(ui_Container1, LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN);
    ui_Label2 = lv_label_create(ui_Container1);
    lv_label_set_text(ui_Label2, "Disconnected:");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFF2E2E), 0);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_12, 0);
    ui_LabelWifiName = lv_label_create(ui_Container1);
    lv_label_set_text(ui_LabelWifiName, "No WiFi");
    lv_obj_set_style_text_font(ui_LabelWifiName, &lv_font_montserrat_14, 0);

    /* IP row */
    ui_Container2 = lv_obj_create(ui_PanelRight);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, lv_pct(100));
    lv_obj_set_height(ui_Container2, LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_COLUMN);
    ui_LabelIP = lv_label_create(ui_Container2);
    lv_label_set_text(ui_LabelIP, "IP:");
    lv_obj_set_style_text_color(ui_LabelIP, lv_color_hex(0xA8A8A8), 0);
    lv_obj_set_style_text_font(ui_LabelIP, &lv_font_montserrat_12, 0);
    ui_LabelIPData = lv_label_create(ui_Container2);
    lv_label_set_text(ui_LabelIPData, "0.0.0.0");
    lv_obj_set_style_text_font(ui_LabelIPData, &lv_font_montserrat_14, 0);

    /* API age — moved to bottom-right of the radar panel (ui_LabelAPIRefreshBig).
       No duplicate here. */

    /* Trail toggle row — switch on the right */
    ui_ContainerTrailRowMain = lv_obj_create(ui_PanelRight);
    lv_obj_remove_style_all(ui_ContainerTrailRowMain);
    lv_obj_set_width(ui_ContainerTrailRowMain, lv_pct(100));
    lv_obj_set_height(ui_ContainerTrailRowMain, 36);
    lv_obj_set_flex_flow(ui_ContainerTrailRowMain, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerTrailRowMain, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    ui_LabelTrailTextMain = lv_label_create(ui_ContainerTrailRowMain);
    lv_label_set_text(ui_LabelTrailTextMain, "Trail (selected)");
    lv_obj_set_style_text_color(ui_LabelTrailTextMain, lv_color_hex(0x7CFFB0), 0);
    lv_obj_set_style_text_font(ui_LabelTrailTextMain, &lv_font_montserrat_16, 0);
    ui_SwitchTrailRowMain = lv_switch_create(ui_ContainerTrailRowMain);
    lv_obj_set_width(ui_SwitchTrailRowMain, 60);
    lv_obj_set_height(ui_SwitchTrailRowMain, 30);
    /* default OFF — LoadTrail() in app_state.c will sync the switch state */

    /* Settings row — gear + "Settings" label, just below the status rows */
    ui_ContainerSettings = lv_obj_create(ui_PanelRight);
    lv_obj_remove_style_all(ui_ContainerSettings);
    lv_obj_set_width(ui_ContainerSettings, lv_pct(100));
    lv_obj_set_height(ui_ContainerSettings, LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(ui_ContainerSettings, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerSettings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_column(ui_ContainerSettings, 8, 0);
    ui_Button1 = lv_btn_create(ui_ContainerSettings);
    lv_obj_set_width(ui_Button1, 32); lv_obj_set_height(ui_Button1, 32);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_img_src(ui_Button1, &ui_img_settings_png, 0);
    lv_obj_set_style_bg_img_recolor(ui_Button1, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_bg_img_recolor_opa(ui_Button1, 255, 0);
    ui_LabelSettings = lv_label_create(ui_ContainerSettings);
    lv_label_set_text(ui_LabelSettings, "Settings");
    lv_obj_set_style_text_color(ui_LabelSettings, lv_color_hex(0x7CFFB0), 0);
    lv_obj_set_style_text_font(ui_LabelSettings, &lv_font_montserrat_14, 0);

    /* category card kept but hidden (OpenSky usually "Unknown") */
    ui_ContainerCard9 = lv_obj_create(ui_PanelRight);
    CARD(ui_ContainerCard9);
    lv_obj_set_width(ui_ContainerCard9, lv_pct(100));
    lv_obj_set_height(ui_ContainerCard9, 40);
    ui_Label25 = lv_label_create(ui_ContainerCard9);
    lv_obj_set_x(ui_Label25, 10); lv_obj_set_y(ui_Label25, 2);
    lv_label_set_text(ui_Label25, "Category");
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_12, 0); GRAY(ui_Label25);
    ui_LabelCraftCategory = lv_label_create(ui_ContainerCard9);
    lv_obj_set_align(ui_LabelCraftCategory, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_x(ui_LabelCraftCategory, 10); lv_obj_set_y(ui_LabelCraftCategory, -4);
    lv_label_set_text(ui_LabelCraftCategory, "—");
    lv_obj_set_style_text_color(ui_LabelCraftCategory, lv_color_hex(0x00A4F9), 0);
    lv_obj_set_style_text_font(ui_LabelCraftCategory, &lv_font_montserrat_16, 0);
    lv_obj_add_flag(ui_ContainerCard9, LV_OBJ_FLAG_HIDDEN);

    /* ============ No more bottom status bar ============ */
    ui_PanelBottom = NULL;  /* kept for uic_ alias compatibility */

    /* API not-configured prompt (overlay) — shown when no credentials */
    ui_DialogConfigReq = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_DialogConfigReq, 320);
    lv_obj_set_height(ui_DialogConfigReq, 120);
    lv_obj_set_align(ui_DialogConfigReq, LV_ALIGN_CENTER);
    lv_obj_set_y(ui_DialogConfigReq, -20);
    lv_obj_clear_flag(ui_DialogConfigReq, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_DialogConfigReq, lv_color_hex(0x1B2147), 0);
    lv_obj_set_style_bg_opa(ui_DialogConfigReq, 255, 0);
    lv_obj_set_style_border_width(ui_DialogConfigReq, 1, 0);
    lv_obj_set_style_border_color(ui_DialogConfigReq, lv_color_hex(0x4E4FE0), 0);
    lv_obj_set_style_pad_all(ui_DialogConfigReq, 10, 0);
    ui_Label5 = lv_label_create(ui_DialogConfigReq);
    lv_obj_set_align(ui_Label5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label5, "API not configured");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_16, 0);
    ui_Label3 = lv_label_create(ui_DialogConfigReq);
    lv_obj_set_width(ui_Label3, lv_pct(95));
    lv_obj_set_align(ui_Label3, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label3, "Connect to the IP shown in the right rail to upload API credentials.");
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_12, 0); GRAY(ui_Label3);
    lv_obj_add_flag(ui_DialogConfigReq, LV_OBJ_FLAG_HIDDEN);  /* shown by main.c when no creds */

#undef CARD
#undef GRAY

    /* ---- event bindings that remain on Screen1 ---- */
    lv_obj_add_event_cb(ui_ButtonRangeUp,     ui_event_ButtonRangeUp,     LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonRangeDown,   ui_event_ButtonRangeDown,   LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonRefreshUp,   ui_event_ButtonRefreshUp,   LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonRefreshDown, ui_event_ButtonRefreshDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1,           ui_event_Button1,           LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Imageradar,        Radar_TapSelect,            LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_SwitchTrailRowMain,    toggleTrail,                LV_EVENT_ALL, NULL);

    /* ---- uic_ aliases owned by Screen1 ---- */
    uic_PanelRadar   = ui_PanelRadar;
    uic_Imageradar   = ui_Imageradar;
    uic_LabelRange   = ui_Label29;
    uic_PanelRight   = ui_PanelRight;
    uic_PanelBottom  = ui_PanelBottom;
    uic_LabelCraftName     = ui_LabelCraftName;
    uic_LabelCraftAlt      = ui_LabelCraftAlt;
    uic_LabelCraftSpeed    = ui_LabelCraftSpeed;
    uic_LabelCraftOrigin   = ui_LabelCraftOrigin;
    uic_LabelCraftCategory = ui_LabelCraftCategory;
    uic_LabelCraftHeading   = ui_LabelCraftHeading;
    uic_LabelCraftClimb     = ui_LabelCraftClimb;
    uic_ContainerCard1 = ui_ContainerCard1;
    uic_LabelPlaneCount = ui_LabelPlaneCount;
    uic_ContainerCard2 = ui_ContainerCard2;
    uic_LabelAPIRefresh = ui_LabelAPIRefresh;
    uic_LabelConnection = ui_Label2;
    uic_LabelWifiName   = ui_LabelWifiName;
    uic_LabelIP         = ui_LabelIP;
    uic_LabelIPData     = ui_LabelIPData;
    uic_DialogConfigReq = ui_DialogConfigReq;
    uic_LabelClock      = ui_LabelClock;
    uic_LabelRange      = ui_Label29;       /* "Range: 50 km" */
    uic_LabelRefresh    = ui_LabelRefresh;  /* "Refresh: 22s" */
}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_ContainerLeft = NULL;
    ui_Container6 = NULL;
    ui_Label21 = NULL;
    ui_Label22 = NULL;
    uic_PanelLeft = NULL;
    ui_PanelLeft = NULL;
    ui_Container3 = NULL;
    ui_Label12 = NULL;
    uic_ContainerCard1 = NULL;
    ui_ContainerCard1 = NULL;
    ui_Label13 = NULL;
    uic_LabelPlaneCount = NULL;
    ui_LabelPlaneCount = NULL;
    ui_Image1 = NULL;
    uic_ContainerCard2 = NULL;
    ui_ContainerCard2 = NULL;
    ui_Label14 = NULL;
    uic_LabelAPIRefresh = NULL;
    ui_LabelAPIRefresh = NULL;
    ui_LabelAPIRefreshBig = NULL;
    ui_LabelWaitingBanner = NULL;
    ui_ContainerLegend = NULL;
    ui_LegendClimb = NULL;
    ui_LegendDescend = NULL;
    ui_LegendGround = NULL;
    ui_LegendLevel = NULL;
    ui_Image2 = NULL;
    ui_PanelLeft1 = NULL;
    ui_Container5 = NULL;
    ui_Label15 = NULL;
    ui_ContainerCard3 = NULL;
    uic_LabelCoords = NULL;
    ui_LabelCoords = NULL;
    ui_Button3 = NULL;
    ui_ContainerCard8 = NULL;
    ui_Label23 = NULL;
    ui_Switch3 = NULL;
    uic_LabelRange = NULL;
    uic_SwitchUnits = NULL;
    ui_ContainerCardUnits = NULL;
    ui_LabelUnits = NULL;
    ui_SwitchUnits = NULL;
    ui_ContainerCardTrail = NULL;
    ui_LabelTrail = NULL;
    ui_SwitchTrail = NULL;
    uic_PanelRight = NULL;
    ui_PanelRight = NULL;
    ui_Container4 = NULL;
    ui_Label1 = NULL;
    ui_ContainerCard4 = NULL;
    ui_Label17 = NULL;
    uic_LabelCraftName = NULL;
    ui_LabelCraftName = NULL;
    ui_ContainerCard5 = NULL;
    ui_Label18 = NULL;
    uic_LabelCraftAlt = NULL;
    ui_LabelCraftAlt = NULL;
    ui_ContainerCard6 = NULL;
    ui_Label19 = NULL;
    uic_LabelCraftSpeed = NULL;
    ui_LabelCraftSpeed = NULL;
    ui_ContainerCard7 = NULL;
    ui_Label20 = NULL;
    uic_LabelCraftOrigin = NULL;
    ui_LabelCraftOrigin = NULL;
    ui_ContainerCard9 = NULL;
    ui_Label25 = NULL;
    uic_LabelCraftCategory = NULL;
    ui_LabelCraftCategory = NULL;
    ui_ContainerCard10 = NULL;
    ui_Label26 = NULL;
    uic_LabelCraftHeading = NULL;
    ui_LabelCraftHeading = NULL;
    uic_LabelCraftClimb = NULL;
    ui_ContainerCardClimb = NULL;
    ui_LabelClimbTitle = NULL;
    ui_LabelCraftClimb = NULL;
    uic_PanelRadar = NULL;
    ui_PanelRadar = NULL;
    uic_Imageradar = NULL;
    ui_Imageradar = NULL;
    uic_ButtonLeft = NULL;
    ui_ButtonLeft = NULL;
    ui_Label7 = NULL;
    uic_ButtonRight = NULL;
    ui_ButtonRight = NULL;
    ui_Label11 = NULL;
    ui_Label29 = NULL;
    ui_ButtonRangeDown = NULL;
    ui_LabelRangeDown = NULL;
    ui_ButtonRangeUp = NULL;
    ui_LabelRangeUp = NULL;
    ui_RadarTitle = NULL;
    ui_RadarLoc = NULL;
    ui_ContainerRange = NULL;
    ui_ContainerRefresh = NULL;
    ui_ButtonRefreshUp = NULL;
    ui_LabelRefreshUp = NULL;
    ui_ButtonRefreshDown = NULL;
    ui_LabelRefreshDown = NULL;
    ui_LabelRefresh = NULL;
    ui_ContainerSettings = NULL;
    ui_LabelSettings = NULL;
    ui_ContainerTrailRowMain = NULL;
    ui_LabelTrailTextMain = NULL;
    ui_SwitchTrailRowMain = NULL;
    uic_PanelBottom = NULL;
    ui_PanelBottom = NULL;
    ui_Button1 = NULL;
    ui_Container1 = NULL;
    uic_LabelConnection = NULL;
    ui_Label2 = NULL;
    uic_LabelWifiName = NULL;
    ui_LabelWifiName = NULL;
    ui_Container2 = NULL;
    uic_LabelIP = NULL;
    ui_LabelIP = NULL;
    uic_LabelIPData = NULL;
    ui_LabelIPData = NULL;
    uic_LabelClock = NULL;
    ui_LabelClock = NULL;
    uic_LabelRefresh = NULL;
    uic_DialogConfigReq = NULL;
    ui_DialogConfigReq = NULL;
    ui_Label3 = NULL;
    ui_Label5 = NULL;
    uic_DialogCoord = NULL;
    ui_DialogCoord = NULL;
    ui_Container10 = NULL;
    ui_Label16 = NULL;
    ui_Container9 = NULL;
    uic_TextLat = NULL;
    ui_TextLat = NULL;
    uic_TextLon = NULL;
    ui_TextLon = NULL;
    ui_Container7 = NULL;
    ui_Button5 = NULL;
    ui_Label27 = NULL;
    ui_Button7 = NULL;
    ui_Label28 = NULL;
    uic_KeyboardCoord = NULL;
    ui_KeyboardCoord = NULL;

}
