// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Flight_radar
//
// Hand-edited: consolidated settings screen (units / show-labels / trail /
// coordinates / WiFi / API). Owns the toggles and the coordinate-edit dialog
// that previously lived on Screen1, so Screen1 can be radar-dominant.

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Button4 = NULL;       /* back (X) */
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_SettingsTitle = NULL;
lv_obj_t * ui_SettingsList = NULL;
/* units row */
lv_obj_t * ui_RowUnits = NULL;
lv_obj_t * ui_LabelUnitsRow = NULL;
lv_obj_t * ui_SwitchUnitsRow = NULL;
/* show-labels row */
lv_obj_t * ui_RowLabels = NULL;
lv_obj_t * ui_LabelLabelsRow = NULL;
lv_obj_t * ui_SwitchLabelsRow = NULL;
/* trail row */
lv_obj_t * ui_RowTrail = NULL;
lv_obj_t * ui_LabelTrailRow = NULL;
lv_obj_t * ui_SwitchTrailRow = NULL;
/* coords row */
lv_obj_t * ui_RowCoords = NULL;
lv_obj_t * ui_LabelCoordsRow = NULL;
lv_obj_t * ui_ButtonEditCoords = NULL;
/* wifi row */
lv_obj_t * ui_RowWifi = NULL;
lv_obj_t * ui_ButtonChangeWifi = NULL;
lv_obj_t * ui_Button8 = NULL;       /* forget wifi */
lv_obj_t * ui_Label9 = NULL;
/* api row */
lv_obj_t * ui_RowApi = NULL;
lv_obj_t * ui_Button9 = NULL;       /* forget api */
lv_obj_t * ui_Label10 = NULL;
/* coordinate edit dialog (owned here) */
lv_obj_t * ui_DialogCoord = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_TextLat = NULL;
lv_obj_t * ui_TextLon = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_Button5 = NULL;       /* save */
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Button7 = NULL;       /* cancel */
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_KeyboardCoord = NULL;
lv_obj_t * ui_LabelChangeWifi = NULL;

// event funtions
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_ButtonChangeWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        forgetWifi(e);
    }
}

void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        forgetAPI(e);
    }
}

// build funtions

static lv_obj_t *make_row(lv_obj_t *parent, const char *title, lv_obj_t **label_out)
{
    lv_obj_t *row = lv_obj_create(parent);
    lv_obj_remove_style_all(row);
    lv_obj_set_width(row, lv_pct(100));
    lv_obj_set_height(row, 46);
    lv_obj_clear_flag(row, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    ui_object_set_themeable_style_property(row, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_CardBG);
    ui_object_set_themeable_style_property(row, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_CardBG);
    lv_obj_set_style_pad_left(row, 12, 0);
    lv_obj_set_style_pad_right(row, 12, 0);

    lv_obj_t *lab = lv_label_create(row);
    lv_obj_set_align(lab, LV_ALIGN_LEFT_MID);
    lv_label_set_text(lab, title);
    ui_object_set_themeable_style_property(lab, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Gray);
    ui_object_set_themeable_style_property(lab, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Gray);
    lv_obj_set_style_text_font(lab, &lv_font_montserrat_14, 0);
    if (label_out) *label_out = lab;
    return row;
}

static lv_obj_t *make_switch(lv_obj_t *row, bool checked)
{
    lv_obj_t *sw = lv_switch_create(row);
    lv_obj_set_width(sw, 50);
    lv_obj_set_height(sw, 25);
    lv_obj_set_align(sw, LV_ALIGN_RIGHT_MID);
    if (checked) lv_obj_add_state(sw, LV_STATE_CHECKED);
    return sw;
}

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x0A1024), 0);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, 0);

    /* title */
    ui_SettingsTitle = lv_label_create(ui_Screen3);
    lv_obj_set_x(ui_SettingsTitle, 16);
    lv_obj_set_y(ui_SettingsTitle, 10);
    lv_label_set_text(ui_SettingsTitle, "Flight Radar · Settings");
    lv_obj_set_style_text_color(ui_SettingsTitle, lv_color_hex(0x08FF00), 0);
    lv_obj_set_style_text_font(ui_SettingsTitle, &lv_font_montserrat_20, 0);

    /* back (X) */
    ui_Button4 = lv_btn_create(ui_Screen3);
    lv_obj_set_height(ui_Button4, 44);
    lv_obj_set_width(ui_Button4, 44);
    lv_obj_set_x(ui_Button4, -10);
    lv_obj_set_y(ui_Button4, 8);
    lv_obj_set_align(ui_Button4, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);
    ui_Label24 = lv_label_create(ui_Button4);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "X");
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_28, 0);

    /* scrollable list of setting rows */
    ui_SettingsList = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_SettingsList);
    lv_obj_set_width(ui_SettingsList, 760);
    lv_obj_set_height(ui_SettingsList, 396);
    lv_obj_set_x(ui_SettingsList, 16);
    lv_obj_set_y(ui_SettingsList, 70);
    lv_obj_set_flex_flow(ui_SettingsList, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SettingsList, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_row(ui_SettingsList, 6, 0);

    /* Units */
    ui_RowUnits = make_row(ui_SettingsList, "Imperial units", &ui_LabelUnitsRow);
    ui_SwitchUnitsRow = make_switch(ui_RowUnits, true);

    /* Show labels */
    ui_RowLabels = make_row(ui_SettingsList, "Show labels", &ui_LabelLabelsRow);
    ui_SwitchLabelsRow = make_switch(ui_RowLabels, true);

    /* Trail row removed — the user requested no GUI control for the
       trail. The trail now lives entirely in code (always off). */

    /* Coordinates */
    ui_RowCoords = lv_obj_create(ui_SettingsList);
    lv_obj_remove_style_all(ui_RowCoords);
    lv_obj_set_width(ui_RowCoords, lv_pct(100));
    lv_obj_set_height(ui_RowCoords, 46);
    lv_obj_clear_flag(ui_RowCoords, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    ui_object_set_themeable_style_property(ui_RowCoords, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_CardBG);
    ui_object_set_themeable_style_property(ui_RowCoords, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_CardBG);
    lv_obj_set_style_pad_left(ui_RowCoords, 12, 0);
    lv_obj_set_style_pad_right(ui_RowCoords, 12, 0);
    lv_obj_t *cl = lv_label_create(ui_RowCoords);
    lv_obj_set_align(cl, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cl, "Coordinates");
    ui_object_set_themeable_style_property(cl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Gray);
    ui_object_set_themeable_style_property(cl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Gray);
    lv_obj_set_style_text_font(cl, &lv_font_montserrat_14, 0);
    ui_LabelCoordsRow = lv_label_create(ui_RowCoords);
    lv_obj_set_align(ui_LabelCoordsRow, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_LabelCoordsRow, 130);
    lv_label_set_text(ui_LabelCoordsRow, "00.0000, 00.0000");
    lv_obj_set_style_text_font(ui_LabelCoordsRow, &lv_font_montserrat_14, 0);
    ui_ButtonEditCoords = lv_btn_create(ui_RowCoords);
    lv_obj_set_width(ui_ButtonEditCoords, 40);
    lv_obj_set_height(ui_ButtonEditCoords, 40);
    lv_obj_set_align(ui_ButtonEditCoords, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_ButtonEditCoords, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_img_src(ui_ButtonEditCoords, &ui_img_edit_24_png, 0);
    lv_obj_set_style_bg_img_recolor(ui_ButtonEditCoords, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_bg_img_recolor_opa(ui_ButtonEditCoords, 255, 0);

    /* WiFi */
    ui_RowWifi = lv_obj_create(ui_SettingsList);
    lv_obj_remove_style_all(ui_RowWifi);
    lv_obj_set_width(ui_RowWifi, lv_pct(100));
    lv_obj_set_height(ui_RowWifi, 46);
    lv_obj_set_flex_flow(ui_RowWifi, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_RowWifi, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_column(ui_RowWifi, 8, 0);
    lv_obj_clear_flag(ui_RowWifi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    ui_object_set_themeable_style_property(ui_RowWifi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_CardBG);
    ui_object_set_themeable_style_property(ui_RowWifi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_CardBG);
    lv_obj_t *wl = lv_label_create(ui_RowWifi);
    lv_label_set_text(wl, "Wi-Fi");
    ui_object_set_themeable_style_property(wl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Gray);
    ui_object_set_themeable_style_property(wl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Gray);
    lv_obj_set_style_text_font(wl, &lv_font_montserrat_14, 0);
    lv_obj_set_flex_grow(wl, 1);
    ui_ButtonChangeWifi = lv_btn_create(ui_RowWifi);
    lv_obj_set_height(ui_ButtonChangeWifi, 36);
    lv_obj_set_width(ui_ButtonChangeWifi, 120);
    lv_obj_clear_flag(ui_ButtonChangeWifi, LV_OBJ_FLAG_SCROLLABLE);
    ui_LabelChangeWifi = lv_label_create(ui_ButtonChangeWifi);
    lv_obj_set_align(ui_LabelChangeWifi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelChangeWifi, "Change");
    ui_Button8 = lv_btn_create(ui_RowWifi);
    lv_obj_set_height(ui_Button8, 36);
    lv_obj_set_width(ui_Button8, 90);
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);
    ui_Label9 = lv_label_create(ui_Button8);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Forget");

    /* API */
    ui_RowApi = lv_obj_create(ui_SettingsList);
    lv_obj_remove_style_all(ui_RowApi);
    lv_obj_set_width(ui_RowApi, lv_pct(100));
    lv_obj_set_height(ui_RowApi, 46);
    lv_obj_set_flex_flow(ui_RowApi, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_RowApi, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RowApi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    ui_object_set_themeable_style_property(ui_RowApi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_CardBG);
    ui_object_set_themeable_style_property(ui_RowApi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_CardBG);
    lv_obj_t *al = lv_label_create(ui_RowApi);
    lv_label_set_text(al, "OpenSky API key");
    ui_object_set_themeable_style_property(al, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Gray);
    ui_object_set_themeable_style_property(al, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Gray);
    lv_obj_set_style_text_font(al, &lv_font_montserrat_14, 0);
    lv_obj_set_flex_grow(al, 1);
    ui_Button9 = lv_btn_create(ui_RowApi);
    lv_obj_set_height(ui_Button9, 36);
    lv_obj_set_width(ui_Button9, 120);
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);
    ui_Label10 = lv_label_create(ui_Button9);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Forget API key");

    /* ---- coordinate edit dialog (hidden overlay on this screen) ---- */
    ui_DialogCoord = lv_obj_create(ui_Screen3);
    lv_obj_set_height(ui_DialogCoord, 414);
    lv_obj_set_width(ui_DialogCoord, lv_pct(100));
    lv_obj_set_align(ui_DialogCoord, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DialogCoord, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_DialogCoord, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_DialogCoord, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_DialogCoord, LV_OBJ_FLAG_SCROLLABLE);

    ui_Container10 = lv_obj_create(ui_DialogCoord);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, lv_pct(50));
    lv_obj_set_height(ui_Container10, lv_pct(95));
    lv_obj_set_flex_flow(ui_Container10, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    ui_Label16 = lv_label_create(ui_Container10);
    lv_obj_set_align(ui_Label16, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label16, "Edit co-ordinates");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_16, 0);

    ui_Container9 = lv_obj_create(ui_Container10);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_height(ui_Container9, LV_SIZE_CONTENT);
    lv_obj_set_width(ui_Container9, LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_row(ui_Container9, 10, 0);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    ui_TextLat = lv_textarea_create(ui_Container9);
    lv_obj_set_width(ui_TextLat, 150);
    lv_textarea_set_placeholder_text(ui_TextLat, "Latitude");
    lv_textarea_set_one_line(ui_TextLat, true);

    ui_TextLon = lv_textarea_create(ui_Container9);
    lv_obj_set_width(ui_TextLon, 150);
    lv_textarea_set_placeholder_text(ui_TextLon, "Longitude");
    lv_textarea_set_one_line(ui_TextLon, true);

    ui_Container7 = lv_obj_create(ui_Container10);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_height(ui_Container7, 50);
    lv_obj_set_width(ui_Container7, lv_pct(100));
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_column(ui_Container7, 20, 0);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    ui_Button5 = lv_btn_create(ui_Container7);
    lv_obj_set_width(ui_Button5, 100);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);
    ui_Label27 = lv_label_create(ui_Button5);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Save");

    ui_Button7 = lv_btn_create(ui_Container7);
    lv_obj_set_width(ui_Button7, 100);
    lv_obj_set_height(ui_Button7, 50);
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);
    ui_Label28 = lv_label_create(ui_Button7);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Cancel");

    ui_KeyboardCoord = lv_keyboard_create(ui_DialogCoord);
    lv_keyboard_set_mode(ui_KeyboardCoord, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardCoord, 360);
    lv_obj_set_height(ui_KeyboardCoord, 300);

    /* ---- bindings ---- */
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonChangeWifi, ui_event_ButtonChangeWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchUnitsRow, ui_event_SwitchUnits, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchLabelsRow, ui_event_Switch3, LV_EVENT_ALL, NULL);
    /* Trail toggle event_cb removed — no GUI control for trail */
    lv_obj_add_event_cb(ui_ButtonEditCoords, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextLat, ui_event_TextLat, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextLon, ui_event_TextLon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardCoord, ui_TextLat);

    /* ---- uic_ aliases now owned by the settings screen ---- */
    uic_SwitchUnits   = ui_SwitchUnitsRow;
    uic_SwitchTrail   = ui_SwitchTrailRow;
    uic_LabelCoords   = ui_LabelCoordsRow;
    uic_DialogCoord   = ui_DialogCoord;
    uic_TextLat       = ui_TextLat;
    uic_TextLon       = ui_TextLon;
    uic_KeyboardCoord = ui_KeyboardCoord;
}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    ui_Screen3 = NULL;
    ui_Button4 = NULL;
    ui_Label24 = NULL;
    ui_SettingsTitle = NULL;
    ui_SettingsList = NULL;
    ui_RowUnits = NULL;
    ui_LabelUnitsRow = NULL;
    ui_SwitchUnitsRow = NULL;
    ui_RowLabels = NULL;
    ui_LabelLabelsRow = NULL;
    ui_SwitchLabelsRow = NULL;
    ui_RowTrail = NULL;
    ui_LabelTrailRow = NULL;
    ui_SwitchTrailRow = NULL;
    ui_RowCoords = NULL;
    ui_LabelCoordsRow = NULL;
    ui_ButtonEditCoords = NULL;
    ui_RowWifi = NULL;
    ui_ButtonChangeWifi = NULL;
    ui_LabelChangeWifi = NULL;
    ui_Button8 = NULL;
    ui_Label9 = NULL;
    ui_RowApi = NULL;
    ui_Button9 = NULL;
    ui_Label10 = NULL;
    ui_DialogCoord = NULL;
    ui_Container10 = NULL;
    ui_Label16 = NULL;
    ui_Container9 = NULL;
    ui_TextLat = NULL;
    ui_TextLon = NULL;
    ui_Container7 = NULL;
    ui_Button5 = NULL;
    ui_Label27 = NULL;
    ui_Button7 = NULL;
    ui_Label28 = NULL;
    ui_KeyboardCoord = NULL;

    /* these aliases were assigned from this screen; clear them so stale
       pointers aren't touched after the screen is destroyed. */
    uic_SwitchUnits = NULL;
    uic_SwitchTrail = NULL;
    uic_LabelCoords = NULL;
    uic_DialogCoord = NULL;
    uic_TextLat = NULL;
    uic_TextLon = NULL;
    uic_KeyboardCoord = NULL;
}